In [19]:
import sys
from pathlib import Path

# Project root directory
project_root = Path.cwd().parent

# Add project root to Python path
sys.path.append(str(project_root))

print(project_root)

c:\Users\Owner\OneDrive\Desktop\experience-centered-ai

In [20]:
# =====================================================
# Experience-Centered AI Analysis
# Notebook 1: Data Loading and Validation
#
# Purpose:
# - Load scoring data exported from Excel
# - Standardize column names
# - Verify Python calculations match Excel results
# =====================================================

import pandas as pd
import numpy as np

from pathlib import Path

from scripts.scoring_utils import (
    clean_columns,
    calculate_weighted_score
)

In [21]:
# Load scoring dataset

df = pd.read_csv("../data/raw/scoring.csv")

df.head()

,company_id,company,industry,experience_intensity,ai_enhancement,repeat_usage,agency_preservation,revenue_capture,network_effects,experience_ai_score
0,1,Peloton,Fitness,10,9,8,9,8,6,8.65
1,2,Planet Fitness,Fitness,7,6,7,8,8,4,6.75
2,3,Duolingo,Education,9,10,10,9,9,7,9.20
3,4,Coursera,Education,8,8,7,8,7,5,7.40
4,5,Roblox,Gaming,10,9,10,10,9,10,9.70

In [22]:
# Standardize column names

df = clean_columns(df)

df.columns

Index(['company_id', 'company', 'industry', 'experience_intensity',
       'ai_enhancement', 'repeat_usage', 'agency_preservation',
       'revenue_capture', 'network_effects', 'experience_ai_score'],
      dtype='str')

In [23]:
# Review data structure and types

df.info()

<class 'pandas.DataFrame'>
RangeIndex: 16 entries, 0 to 15
Data columns (total 10 columns):
 #   Column                Non-Null Count  Dtype
---  ------                --------------  -----
 0   company_id            16 non-null     int64
 1   company               16 non-null     str
 2   industry              16 non-null     str
 3   experience_intensity  16 non-null     int64
 4   ai_enhancement        16 non-null     int64
 5   repeat_usage          16 non-null     int64
 6   agency_preservation   16 non-null     int64
 7   revenue_capture       16 non-null     int64
 8   network_effects       16 non-null     int64
 9   experience_ai_score   16 non-null     float64
dtypes: float64(1), int64(7), str(2)
memory usage: 1.4 KB

In [24]:
# Recalculate scores using Python implementation
# This verifies that the Excel calculations were exported correctly

df = calculate_weighted_score(df)

df[
    [
        "company",
        "experience_ai_score",
        "python_score"
    ]
]

             company  experience_ai_score  python_score
0            Peloton                 8.65          8.65
1     Planet Fitness                 6.75          6.75
2           Duolingo                 9.20          9.20
3           Coursera                 7.40          7.40
4             Roblox                 9.70          9.70
5    Electronic Arts                 8.25          8.25
6             Intuit                 7.25          7.25
7               SoFi                 6.70          6.70
8             Airbnb                 7.70          7.70
9   Booking Holdings                 6.60          6.60
10            Netlix                 7.95          7.95
11           Spotify                 8.35          8.35
12        HelloFresh                 7.75          7.75
13        Sweetgreen                 6.40          6.40
14       Match Group                 8.85          8.85
15            Bumble                 8.65          8.65

In [25]:
# Compare Excel scores against Python scores

df["difference"] = (
    df["experience_ai_score"]
    - df["python_score"]
)

df[
    [
        "company",
        "experience_ai_score",
        "python_score",
        "difference"
    ]
]

             company  experience_ai_score  python_score    difference
0            Peloton                 8.65          8.65  0.000000e+00
1     Planet Fitness                 6.75          6.75 -8.881784e-16
2           Duolingo                 9.20          9.20  0.000000e+00
3           Coursera                 7.40          7.40  0.000000e+00
4             Roblox                 9.70          9.70  0.000000e+00
5    Electronic Arts                 8.25          8.25  0.000000e+00
6             Intuit                 7.25          7.25  0.000000e+00
7               SoFi                 6.70          6.70  0.000000e+00
8             Airbnb                 7.70          7.70  0.000000e+00
9   Booking Holdings                 6.60          6.60 -8.881784e-16
10            Netlix                 7.95          7.95 -8.881784e-16
11           Spotify                 8.35          8.35  0.000000e+00
12        HelloFresh                 7.75          7.75  0.000000e+00
13        Sweetgreen                 6.40          6.40  0.000000e+00
14       Match Group                 8.85          8.85  0.000000e+00
15            Bumble                 8.65          8.65  0.000000e+00

In [26]:
# Summary statistics for validation

df["difference"].describe()

count    1.600000e+01
mean    -1.665335e-16
std      3.580362e-16
min     -8.881784e-16
25%      0.000000e+00
50%      0.000000e+00
75%      0.000000e+00
max      0.000000e+00
Name: difference, dtype: float64

## Score Validation Results

Python-generated scores matched the original Excel calculations.

Observed differences were effectively zero and attributable to floating-point precision.

This validation confirms that subsequent analysis is based on a reproducible implementation of the Experience-Centered AI scoring framework.